version: "3.9"

services:
  backend:
    build: ./backend
    container_name: sf_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  frontend:
    build: ./frontend
    container_name: sf_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  redis:
    image: redis:8.6
    container_name: sf_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: sf_postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
