"""Initial migration stable

Revision ID: 676586e77f47
Revises: 
Create Date: 2026-04-22 14:03:46.847737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '676586e77f47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bannerImage', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PUBLIC', 'PRIVATE', name='announcementtype', native_enum=False), server_default='PUBLIC', nullable=False),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='announcementstatus', native_enum=False), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('standards', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('highlights', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('isPaid', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.Enum('OFFLINE', 'ONLINE', name='coursemode', native_enum=False), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'SPOKEN', 'CLOSED', 'CONVERTED', name='enquirystatus', native_enum=False), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('mediaType', sa.Enum('MEDIA_LIBRARY', 'ASSIGNMENT', 'STUDY_RESOURCE', 'LEARNING_HUB', 'ANNOUNCEMENT', 'BLOG', 'STUDENT', 'EVENT', 'USER', 'COURSE', 'TEST', 'TESTIMONIAL', 'ENQUIRY', name='mediatype', native_enum=False), nullable=False),
    sa.Column('originalFilename', sa.String(), nullable=False),
    sa.Column('filePath', sa.String(), nullable=False),
    sa.Column('contentType', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('passwordHash', sa.String(), nullable=True),
    sa.Column('authServiceProvider', sa.Enum('GOOGLE', 'APP', 'ADMIN', 'TEACHER', name='authserviceprovider'), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole', native_enum=False), server_default='STUDENT', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_pending_users_email'), 'pending_users', ['email'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('featuredImage', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISH', name='blogpoststatus', native_enum=False), nullable=False),
    sa.Column('metaTitle', sa.String(), nullable=True),
    sa.Column('metaDescription', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publishedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.create_table('site_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('academyName', sa.String(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=False),
    sa.Column('contactDetails', sa.Text(), nullable=True),
    sa.Column('phoneNumbers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('workingHours', sa.Text(), nullable=False),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('studentName', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('courseName', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=True),
    sa.Column('authServiceProvider', sa.Enum('GOOGLE', 'APP', 'ADMIN', 'TEACHER', name='authserviceprovider'), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole', native_enum=False), server_default='STUDENT', nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('refreshToken', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastLogIn', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('course_categories',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'category_id')
    )
    op.create_table('post_categories',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rollNo', sa.String(), nullable=True),
    sa.Column('standard', sa.String(), nullable=True),
    sa.Column('schoolName', sa.String(), nullable=True),
    sa.Column('board', sa.String(), nullable=True),
    sa.Column('parentName', sa.String(), nullable=True),
    sa.Column('parentMobileNumber', sa.String(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('teacherId', sa.UUID(), nullable=True),
    sa.Column('courseId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['teacherId'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_hub_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('youtubeLink', sa.String(), nullable=False),
    sa.Column('youtubeVideoId', sa.String(), nullable=False),
    sa.Column('videoType', sa.Enum('EDUCATIONAL_EXPLANATION', 'SHORT_CONCEPT', 'EXAM_PREPARATION_GUIDANCE', name='learninghubvideotype', native_enum=False), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('publishDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subjectId', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['subjectId'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_hub_videos_youtubeVideoId'), 'learning_hub_videos', ['youtubeVideoId'], unique=False)
    op.create_table('lectures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lectureTitle', sa.String(), nullable=True),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subjectId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subjectId'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('razorpayOrderId', sa.String(), nullable=False),
    sa.Column('razorpayPaymentId', sa.String(), nullable=True),
    sa.Column('razorpaySignature', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.Column('courseId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpayOrderId')
    )
    op.create_table('student_courses',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.create_table('tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('totalMarks', sa.Integer(), nullable=False),
    sa.Column('durationMinutes', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.Enum('OFFLINE', 'ONLINE', name='testmode', native_enum=False), nullable=False),
    sa.Column('type', sa.Enum('ChapterWise', 'FullSyllabus', name='testtype', native_enum=False), nullable=False),
    sa.Column('subjectId', sa.UUID(), nullable=False),
    sa.Column('teacherId', sa.UUID(), nullable=False),
    sa.Column('maxAttempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='teststatus', native_enum=False), server_default='draft', nullable=False),
    sa.ForeignKeyConstraint(['subjectId'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacherId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lectureId', sa.UUID(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lectureId'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecture_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus', native_enum=False), nullable=False),
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.Column('lectureId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lectureId'], ['lectures.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId', 'lectureId', name='uq_student_lecture')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('questionText', sa.String(), nullable=True),
    sa.Column('questionImage', sa.String(), nullable=True),
    sa.Column('optionA', sa.String(), nullable=True),
    sa.Column('optionAImg', sa.String(), nullable=True),
    sa.Column('optionB', sa.String(), nullable=True),
    sa.Column('optionBImg', sa.String(), nullable=True),
    sa.Column('optionC', sa.String(), nullable=True),
    sa.Column('optionCImg', sa.String(), nullable=True),
    sa.Column('optionD', sa.String(), nullable=True),
    sa.Column('optionDImg', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('explanationImg', sa.String(), nullable=True),
    sa.Column('correctAnswer', sa.Enum('A', 'B', 'C', 'D', name='mcqanswer', native_enum=False), nullable=True),
    sa.Column('correctImg', sa.String(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.Column('testId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['testId'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('lectureId', sa.UUID(), nullable=True),
    sa.Column('subjectId', sa.UUID(), nullable=True),
    sa.Column('filePath', sa.String(), nullable=False),
    sa.Column('uploadAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lectureId'], ['lectures.id'], ),
    sa.ForeignKeyConstraint(['subjectId'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('testId', sa.UUID(), nullable=False),
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('obtainedMarks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['testId'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.Enum('A', 'B', 'C', 'D', name='mcqanswer', native_enum=False), nullable=True),
    sa.Column('testId', sa.UUID(), nullable=False),
    sa.Column('questionId', sa.UUID(), nullable=False),
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['questionId'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['testId'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId', 'questionId', 'testId', name='uq_student_tests')
    )
    op.create_table('student_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignmentId', sa.UUID(), nullable=False),
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NO_ACTIONS', 'PENDING', 'EXCUSED', 'INCOMPLETE', 'COMPLETE', 'REJECTED', name='assignmentstatus', native_enum=False), nullable=False),
    sa.Column('filePath', sa.String(), nullable=False),
    sa.Column('uploadAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignmentId'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId', 'assignmentId', name='uq_student_assignment')
    )
    op.create_table('study_resource_categories',
    sa.Column('study_resource_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_resource_id'], ['study_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_resource_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_resource_categories')
    op.drop_table('student_assignments')
    op.drop_table('student_answers')
    op.drop_table('test_attempts')
    op.drop_table('study_resources')
    op.drop_table('questions')
    op.drop_table('lecture_attendance')
    op.drop_table('assignments')
    op.drop_table('tests')
    op.drop_table('student_courses')
    op.drop_table('payments')
    op.drop_table('lectures')
    op.drop_index(op.f('ix_learning_hub_videos_youtubeVideoId'), table_name='learning_hub_videos')
    op.drop_table('learning_hub_videos')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('post_tags')
    op.drop_table('post_categories')
    op.drop_table('course_categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('testimonials')
    op.drop_table('tags')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_pending_users_email'), table_name='pending_users')
    op.drop_table('pending_users')
    op.drop_table('media_assets')
    op.drop_table('enquiries')
    op.drop_table('courses')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('announcements')
    # ### end Alembic commands ###
